# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payload.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'proto/payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import utility_pb2 as proto_dot_utility__pb2

from proto.utility_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/payload.proto\x12\x07payload\x1a\x13proto/utility.proto\"\xc7\x03\n\x0ePayloadMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08senderId\x18\x02 \x01(\t\x12+\n\x0fsenderIpAddress\x18\x03 \x01(\x0b\x32\x12.utility.IpAddress\x12)\n\x0bpayloadType\x18\x04 \x01(\x0e\x32\x14.payload.PayloadType\x12\x35\n\x10\x64iscoveryRequest\x18\x06 \x01(\x0b\x32\x19.payload.DiscoveryRequestH\x00\x12\x37\n\x11\x64iscoveryResponse\x18\x07 \x01(\x0b\x32\x1a.payload.DiscoveryResponseH\x00\x12+\n\x0btaskRequest\x18\x08 \x01(\x0b\x32\x14.payload.TaskRequestH\x00\x12-\n\x0ctaskResponse\x18\t \x01(\x0b\x32\x15.payload.TaskResponseH\x00\x12\x33\n\x0f\x61\x63knowledgement\x18\n \x01(\x0b\x32\x18.payload.AcknowledgementH\x00\x12-\n\x0cregistration\x18\x0b \x01(\x0b\x32\x15.payload.RegistrationH\x00\x42\x0f\n\rpayloadObject\"B\n\x11\x44iscoveryResponse\x12-\n\x0e\x61vailablePeers\x18\x01 \x01(\x0b\x32\x15.utility.AddressTable\"*\n\x10\x44iscoveryRequest\x12\x16\n\x0epeersRequested\x18\x01 \x01(\x05\"\xbd\x01\n\x0bTaskRequest\x12\x12\n\nnumWorkers\x18\x01 \x01(\x05\x12\x12\n\nleaderUuid\x18\x02 \x01(\t\x12.\n\x0f\x61ssignedWorkers\x18\x03 \x01(\x0b\x32\x15.utility.AddressTable\x12\x16\n\x0cglob_pattern\x18\x04 \x01(\tH\x00\x12&\n\x1ctraining_data_index_filename\x18\x05 \x01(\tH\x00\x42\x16\n\x14training_data_source\"4\n\x0cTrainingData\x12$\n\x1ctraining_data_index_filename\x18\x01 \x01(\t\"-\n\x13\x41ggregatorInputData\x12\x16\n\x0emodelStateDict\x18\x01 \x01(\x0c\"&\n\x0cTaskResponse\x12\x16\n\x0emodelStateDict\x18\x01 \x01(\x0c\"\x11\n\x0f\x41\x63knowledgement\"\x0e\n\x0cRegistration*\x88\x01\n\x0bPayloadType\x12\x13\n\x0f\x41\x43KNOWLEDGEMENT\x10\x00\x12\x10\n\x0cREGISTRATION\x10\x01\x12\x15\n\x11\x44ISCOVERY_REQUEST\x10\x02\x12\x16\n\x12\x44ISCOVERY_RESPONSE\x10\x03\x12\x10\n\x0cTASK_REQUEST\x10\x04\x12\x11\n\rTASK_RESPONSE\x10\x05P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOADTYPE']._serialized_start=992
  _globals['_PAYLOADTYPE']._serialized_end=1128
  _globals['_PAYLOADMESSAGE']._serialized_start=54
  _globals['_PAYLOADMESSAGE']._serialized_end=509
  _globals['_DISCOVERYRESPONSE']._serialized_start=511
  _globals['_DISCOVERYRESPONSE']._serialized_end=577
  _globals['_DISCOVERYREQUEST']._serialized_start=579
  _globals['_DISCOVERYREQUEST']._serialized_end=621
  _globals['_TASKREQUEST']._serialized_start=624
  _globals['_TASKREQUEST']._serialized_end=813
  _globals['_TRAININGDATA']._serialized_start=815
  _globals['_TRAININGDATA']._serialized_end=867
  _globals['_AGGREGATORINPUTDATA']._serialized_start=869
  _globals['_AGGREGATORINPUTDATA']._serialized_end=914
  _globals['_TASKRESPONSE']._serialized_start=916
  _globals['_TASKRESPONSE']._serialized_end=954
  _globals['_ACKNOWLEDGEMENT']._serialized_start=956
  _globals['_ACKNOWLEDGEMENT']._serialized_end=973
  _globals['_REGISTRATION']._serialized_start=975
  _globals['_REGISTRATION']._serialized_end=989
# @@protoc_insertion_point(module_scope)
