# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/utility.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/utility.proto',
  package='utility',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13proto/utility.proto\x12\x07utility\"%\n\tIpAddress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\x97\x01\n\x0c\x41\x64\x64ressTable\x12>\n\raddress_table\x18\x01 \x03(\x0b\x32\'.utility.AddressTable.AddressTableEntry\x1aG\n\x11\x41\x64\x64ressTableEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.utility.IpAddress:\x02\x38\x01\x62\x06proto3')
)




_IPADDRESS = _descriptor.Descriptor(
  name='IpAddress',
  full_name='utility.IpAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='utility.IpAddress.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='utility.IpAddress.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=69,
)


_ADDRESSTABLE_ADDRESSTABLEENTRY = _descriptor.Descriptor(
  name='AddressTableEntry',
  full_name='utility.AddressTable.AddressTableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='utility.AddressTable.AddressTableEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='utility.AddressTable.AddressTableEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=223,
)

_ADDRESSTABLE = _descriptor.Descriptor(
  name='AddressTable',
  full_name='utility.AddressTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_table', full_name='utility.AddressTable.address_table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADDRESSTABLE_ADDRESSTABLEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=223,
)

_ADDRESSTABLE_ADDRESSTABLEENTRY.fields_by_name['value'].message_type = _IPADDRESS
_ADDRESSTABLE_ADDRESSTABLEENTRY.containing_type = _ADDRESSTABLE
_ADDRESSTABLE.fields_by_name['address_table'].message_type = _ADDRESSTABLE_ADDRESSTABLEENTRY
DESCRIPTOR.message_types_by_name['IpAddress'] = _IPADDRESS
DESCRIPTOR.message_types_by_name['AddressTable'] = _ADDRESSTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IpAddress = _reflection.GeneratedProtocolMessageType('IpAddress', (_message.Message,), dict(
  DESCRIPTOR = _IPADDRESS,
  __module__ = 'proto.utility_pb2'
  # @@protoc_insertion_point(class_scope:utility.IpAddress)
  ))
_sym_db.RegisterMessage(IpAddress)

AddressTable = _reflection.GeneratedProtocolMessageType('AddressTable', (_message.Message,), dict(

  AddressTableEntry = _reflection.GeneratedProtocolMessageType('AddressTableEntry', (_message.Message,), dict(
    DESCRIPTOR = _ADDRESSTABLE_ADDRESSTABLEENTRY,
    __module__ = 'proto.utility_pb2'
    # @@protoc_insertion_point(class_scope:utility.AddressTable.AddressTableEntry)
    ))
  ,
  DESCRIPTOR = _ADDRESSTABLE,
  __module__ = 'proto.utility_pb2'
  # @@protoc_insertion_point(class_scope:utility.AddressTable)
  ))
_sym_db.RegisterMessage(AddressTable)
_sym_db.RegisterMessage(AddressTable.AddressTableEntry)


_ADDRESSTABLE_ADDRESSTABLEENTRY._options = None
# @@protoc_insertion_point(module_scope)
